# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build
          command: yarn build

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish:
          context: github
          requires:
            - build
          filters:
            branches:
              only: master


